import React from 'react';
import './__tpl_name__.__tpl_cfg_css__';

const propTypes = {
	
};

class __tpl_name__ extends React.Component {
	render () {
		return <div className='__tpl_name__'>
			<h1>Component: __tpl_name__</h1>
			<h3>Generated by react-mogen</h3>
		</div>;
	}
}

__tpl_name__.propTypes = propTypes;
export default __tpl_name__;